#!/bin/sh
### BEGIN INIT INFO
# Provides:          candy
# Required-Start:
# Required-Stop:
# Default-Start: S 2 3 4 5
# Default-Stop:
# Short-Description: Candy-point Managment
# Description:
### END INIT INFO

. /lib/lsb/init-functions

case "$1" in
  start)
    log_daemon_msg "Starting candy-point service..."
    cd /
    cd home/pi/
    python acid0.py
    cd /
    log_end_msg 0
    ;;
  stop)
    ;;
  restart)
    ;;
  force-reload)
    ;;
  *)
    echo "Usage: $0 start" >&2
    exit 3
    ;;
esac

